### PR TITLE
Revert v1.2.2 changes that caused some breakage.

### PR DESCRIPTION
**Pull request by paulbsch**

### CODE REVIEW

**Review by lee-baines — APPROVED** [review]

**Comment by lee-baines** [comment]
You can ignore the mend and snyk security checks as I'd expect those to fail

**Comment by pearj** [comment]
What broke in v1.2.2? I'm use Azure as a backend, and I'd already updated some of our environments to v1.2.2, I think I had some issues, but I fixed them by deleting the namespace that secret-agent was running in and redeploying.

**Comment by lee-baines** [comment]
Hi @pearj, there were some issues raised from customers saying the secrets defined in the secretagentconfiguration weren't automatically being backed up to Azure Vault. There was also some issues with AWS.  As v1.2.2 was quite a large change, we've had to revert it and reapply the patches separately.  Apologies for any disruption

**Comment by lee-baines** [comment]
Yes would be sensible for now, then look out for an updated release soon

**Pull request merged**
