### PR TITLE
Updates vulnerable pkgs

### PR DESCRIPTION
**Pull request by dnitsch**
fix: update all the cloudprovider libs
update k8s.io and controller runtime
should address most of the vulnerabilities

### CODE REVIEW

**Review by lee-baines — APPROVED** [review]
Looks good. Thanks

**Comment by lee-baines** [comment]
@dnitsch I've fixed 1 of ci failures but there is another 1 with the tests.  I'm trying to get a release out but I'll look at this as soon as I can

**Comment by dnitsch** [comment]
ah sorry @lee-baines  - just came around to getting back to this. I'll take a look now and will update here if any issues as soon as I can.

**Comment by dnitsch** [comment]
righto @lee-baines this seems to work now with the last change to the test framework. 

I think at some point once this is released, we should probably remove the setup-envtest script from k8s-sigs as it's no longer there and just use straight KIND like you do now with the flags into to the tests to use a pre-existing cluster (kind on the job node)

anyways, please take a look and if you could merge it in and cut a new version when you get a sec.

**Comment by lee-baines** [comment]
Thanks for sorting @dnitsch.

**Comment by lee-baines** [comment]
New release version v1.2.2 has been published. I'll update forgeops to point to the new version of secret-agent

**Comment by dnitsch** [comment]
> New release version v1.2.2 has been published. I'll update forgeops to point to the new version of secret-agent

Perfect thanks @lee-baines

**Pull request merged**
