### PR TITLE
fix: add KMSKeyId option to AWS Secrets Manager

### PR DESCRIPTION
**Pull request by dnitsch**
Adds the ability to supply own KMS key for secret creation.

Addresses #226 

@lee-baines or @jrcast you seem to be still somewhat active on this - any chance of a review on this please?

### CODE REVIEW

**Comment by lee-baines** [comment]
Hi @dnitsch, thanks for the PR. Nice addition

**Comment by dnitsch** [comment]
> Hi @dnitsch, thanks for the PR. Nice addition

Thanks @lee-baines  - do you know if it can be approved and a new version released soon - as it is a bit of a blocker for a few projects.

**Comment by ekartsonakisamido** [comment]
👍

**Review by lee-baines — APPROVED** [review]

**Comment by lee-baines** [comment]
Hi, apologies for not getting onto this earlier.  I've approve the PR.  But we're require signed commits to be able to merge so can you please sign the commit and I can get it merged.

**Comment by dnitsch** [comment]
> Hi, apologies for not getting onto this earlier. I've approve the PR. But we're require signed commits to be able to merge so can you please sign the commit and I can get it merged.

ah sorry rebasing signed now - not sure why it didn't sign as I have it globally enabled... anyway

**Comment by dnitsch** [comment]
@lee-baines done - and thanks again for your help on this.

**Comment by dnitsch** [comment]
@lee-baines  sorry to come back to this - but do you think you can cut a new version or is that something we should do temporarily to get the latest controller code in?

**Comment by lee-baines** [comment]
I have published a new release including this change

**Comment by dnitsch** [comment]
Amazing thanks @lee-baines

**Pull request merged**
